package global

var ExcludedApps = map[string]bool{
	"cmd.exe":                    true,
	"powershell.exe":             true,
	"powershell_ise.exe":         true,
	"mstsc.exe":                  true,
	"psr.exe":                    true,
	"charmap.exe":                true,
	"wmplayer.exe":               true,
	"cleanmgr.exe":               true,
	"MdSched.exe":                true,
	"odbcad32.exe":               true,
	"RecoveryDrive.exe":          true,
	"regedit.exe":                true,
	"msconfig.exe":               true,
	"msinfo32.exe":               true,
	"dfrgui.exe":                 true,
	"iscsicpl.exe":               true,
	"filemgmt.dll":               true,
	"Taskmgr.exe":                true,
	"appverif.exe":               true,
	"appverif.chm":               true,
	"appcertui.exe":              true,
	"msiexec.exe":                true,
	"LiveCaptions.exe":           true,
	"magnify.exe":                true,
	"narrator.exe":               true,
	"osk.exe":                    true,
	"voiceaccess.exe":            true,
	"explorer.exe":               true,
	"WindowsPowerShell":          true,
	"Windows PowerShell (x86)":   true,
	"Developer Command Prompt":   true,
	"Developer PowerShell":       true,
	"x64 Native Tools":           true,
	"x86 Native Tools":           true,
	"x64_x86 Cross Tools":        true,
	"x86_x64 Cross Tools":        true,
	"MinGW Command Prompt":       true,
	"Modify or Remove MinGW":     true,
	"Debuggable Package Manager": true,
	"Command Prompt":             true,
	"Control Panel":              true,
	"Run":                        true,
	"File Explorer":              true,
	"Uninstall":                  true,
	"Settings":                   true,
}
